/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "TestsSpritf.check" instead.
 */

#include <check.h>
#line 1 "TestsSpritf.check"
#include <stdio.h>
#include <stdlib.h>

#include "../../s21_string.h"

START_TEST(s21_sprintf_one_c) {
#line 6
  char buffer1[100] = {'\0'};
  char buffer2[100] = {'\0'};
  int c_spec_test = sprintf(buffer1, "%c", 'a');
  int _c_spec_test = s21_sprintf(buffer2, "%c", 'a');
  int c_spec_test_2 = sprintf(buffer1, "%-10c", 'T');
  int _c_spec_test_2 = s21_sprintf(buffer2, "%-10c", 'T');
  int c_spec_test_3 = sprintf(buffer1, "%8c", 'g');
  int _c_spec_test_3 = s21_sprintf(buffer2, "%8c", 'g');
  int percent_spec_test = sprintf(buffer1, "%%");
  int _percent_spec_test = s21_sprintf(buffer2, "%%");
  ck_assert_int_eq(c_spec_test, _c_spec_test);
  ck_assert_int_eq(c_spec_test_2, _c_spec_test_2);
  ck_assert_int_eq(c_spec_test_3, _c_spec_test_3);
  ck_assert_int_eq(percent_spec_test, _percent_spec_test);
}
END_TEST

START_TEST(s21_sprintf_two_d) {
#line 23
  char buffer1[100] = {'\0'};
  char buffer2[100] = {'\0'};
  int d_spec_test = sprintf(buffer1, "%hd", (short int)123);
  int _d_spec_test = s21_sprintf(buffer2, "%hd", (short int)123);
  int d_spec_test_2 = sprintf(buffer1, "%0+18d", 123);
  int _d_spec_test_2 = s21_sprintf(buffer2, "%0+18d", 123);
  int d_spec_test_3 = sprintf(buffer1, "%- 18d", 123);
  int _d_spec_test_3 = s21_sprintf(buffer2, "%- 18d", 123);
  int d_spec_test_4 = sprintf(buffer1, "%*d", 4, 10);
  int _d_spec_test_4 = s21_sprintf(buffer2, "%*d", 4, 10);
  int d_spec_test_5 = sprintf(buffer1, "%d", 4);
  int _d_spec_test_5 = s21_sprintf(buffer2, "%d", 4);
  int d_spec_test_6 = sprintf(buffer1, "%d", 0);
  int _d_spec_test_6 = s21_sprintf(buffer2, "%d", 0);
  ck_assert_int_eq(d_spec_test, _d_spec_test);
  ck_assert_int_eq(d_spec_test_2, _d_spec_test_2);
  ck_assert_int_eq(d_spec_test_3, _d_spec_test_3);
  ck_assert_int_eq(d_spec_test_4, _d_spec_test_4);
  ck_assert_int_eq(d_spec_test_5, _d_spec_test_5);
  ck_assert_int_eq(d_spec_test_6, _d_spec_test_6);
}
END_TEST

START_TEST(s21_sprintf_three_f) {
#line 45
  char buffer1[1000] = {'\0'};
  char buffer2[1000] = {'\0'};
  int f_spec_test = sprintf(buffer1, "%f", (float)12);
  int _f_spec_test = s21_sprintf(buffer2, "%f", (float)12);
  int f_spec_test_2 = sprintf(buffer1, "%.0f", (float)12);
  int _f_spec_test_2 = s21_sprintf(buffer2, "%.0f", (float)12);
  int f_spec_test_3 = sprintf(buffer1, "%#.12f", (float)12);
  int _f_spec_test_3 = s21_sprintf(buffer2, "%#.12f", (float)12);
  int f_spec_test_4 = sprintf(buffer1, "%.*f", 4, 1000000.0);
  int _f_spec_test_4 = s21_sprintf(buffer2, "%.*f", 4, 1000000.0);
  ck_assert_int_eq(f_spec_test, _f_spec_test);
  ck_assert_int_eq(f_spec_test_2, _f_spec_test_2);
  ck_assert_int_eq(f_spec_test_3, _f_spec_test_3);
  ck_assert_int_eq(f_spec_test_4, _f_spec_test_4);
}
END_TEST

START_TEST(s21_sprintf_four_s) {
#line 62
  char buffer1[100] = {'\0'};
  char buffer2[100] = {'\0'};
  int s_spec_test = sprintf(buffer1, "%10s", "asd");
  int _s_spec_test = s21_sprintf(buffer2, "%10s", "asd");
  int s_spec_test_2 = sprintf(buffer1, "%5s", "o_o");
  int _s_spec_test_2 = s21_sprintf(buffer2, "%5s", "o_o");
  int s_spec_test_3 = sprintf(buffer1, "%-10s", "  asd");
  int _s_spec_test_3 = s21_sprintf(buffer2, "%-10s", "  asd");
  ck_assert_int_eq(s_spec_test, _s_spec_test);
  ck_assert_int_eq(s_spec_test_2, _s_spec_test_2);
  ck_assert_int_eq(s_spec_test_3, _s_spec_test_3);
}
END_TEST

START_TEST(s21_sprintf_five_u) {
#line 75
  char buffer1[100] = {'\0'};
  char buffer2[100] = {'\0'};
  int u_spec_test = sprintf(buffer1, "%10u", 123);
  int _u_spec_test = s21_sprintf(buffer2, "%10u", 123);
  int u_spec_test_2 = sprintf(buffer1, "%-10u", 123);
  int _u_spec_test_2 = s21_sprintf(buffer2, "%-10u", 123);
  int u_spec_test_3 = sprintf(buffer1, "%3u", 123);
  int _u_spec_test_3 = s21_sprintf(buffer2, "%3u", 123);
  ck_assert_int_eq(u_spec_test, _u_spec_test);
  ck_assert_int_eq(u_spec_test_2, _u_spec_test_2);
  ck_assert_int_eq(u_spec_test_3, _u_spec_test_3);
}
END_TEST

START_TEST(s21_sprintf_six_e) {
#line 88
  char buffer1[1000] = {'\0'};
  char buffer2[1000] = {'\0'};
  int spec_e_double_test = sprintf(buffer1, "%.0e", -0.0123);
  int _spec_e_double_test = s21_sprintf(buffer2, "%.0e", -0.0123);
  int spec_e_double_test_2 = sprintf(buffer1, "%#.0e", (double)1);
  int _spec_e_double_test_2 = s21_sprintf(buffer2, "%#.0e", (double)1);
  int spec_e_double_test_3 =
      sprintf(buffer1, "%.0e %.2e", (double)1, (-0.0123));
  int _spec_e_double_test_3 =
      s21_sprintf(buffer2, "%.0e %.2e", (double)1, (-0.0123));
  int spec_e_double_test_4 = sprintf(buffer1, "%.0E", -0.0123);
  int _spec_e_double_test_4 = s21_sprintf(buffer2, "%.0E", -0.0123);
  int spec_e_double_test_5 = sprintf(buffer1, "%-.0e", -0.0123);
  int _spec_e_double_test_5 = s21_sprintf(buffer2, "%-.0e", -0.0123);
  int spec_e_double_test_6 = sprintf(buffer1, "%.0e", 1000.10);
  int _spec_e_double_test_6 = s21_sprintf(buffer2, "%.0e", 1000.10);

  ck_assert_int_eq(spec_e_double_test, _spec_e_double_test);
  ck_assert_int_eq(spec_e_double_test_2, _spec_e_double_test_2);
  ck_assert_int_eq(spec_e_double_test_3, _spec_e_double_test_3);
  ck_assert_int_eq(spec_e_double_test_4, _spec_e_double_test_4);
  ck_assert_int_eq(spec_e_double_test_5, _spec_e_double_test_5);
  ck_assert_int_eq(spec_e_double_test_6, _spec_e_double_test_6);
}
END_TEST

START_TEST(s21_sprintf_seven_x) {
#line 113
  char buffer1[1000] = {'\0'};
  char buffer2[1000] = {'\0'};
  int spec_X_test = sprintf(buffer1, "%X", 1234678);
  int _spec_X_test = s21_sprintf(buffer2, "%X", 1234678);
  int spec_X_test_2 = sprintf(buffer1, "%6X", 1234678);
  int _spec_X_test_2 = s21_sprintf(buffer2, "%6X", 1234678);
  int spec_X_test_3 = sprintf(buffer1, "%-x", 1234678);
  int _spec_X_test_3 = s21_sprintf(buffer2, "%-x", 1234678);

  ck_assert_int_eq(spec_X_test, _spec_X_test);
  ck_assert_int_eq(spec_X_test_2, _spec_X_test_2);
  ck_assert_int_eq(spec_X_test_3, _spec_X_test_3);
}
END_TEST

START_TEST(s21_sprintf_eight_o) {
#line 127
  char buffer1[1000] = {'\0'};
  char buffer2[1000] = {'\0'};
  int o_spec_test = sprintf(buffer1, "%o", 1234);
  int _o_spec_test = s21_sprintf(buffer2, "%o", 1234);
  int o_spec_test_2 = sprintf(buffer1, "%10o", 1234);
  int _o_spec_test_2 = s21_sprintf(buffer2, "%10o", 1234);
  int o_spec_test_3 = sprintf(buffer1, "%4o", 1234);
  int _o_spec_test_3 = s21_sprintf(buffer2, "%4o", 1234);
  int o_spec_test_4 = sprintf(buffer1, "%-10o", 1234);
  int _o_spec_test_4 = s21_sprintf(buffer2, "%-10o", 1234);
  ck_assert_int_eq(o_spec_test, _o_spec_test);
  ck_assert_int_eq(o_spec_test_2, _o_spec_test_2);
  ck_assert_int_eq(o_spec_test_3, _o_spec_test_3);
  ck_assert_int_eq(o_spec_test_4, _o_spec_test_4);
}
END_TEST

START_TEST(s21_sprintf_nine_g) {
#line 143
  char buffer1[1000] = {'\0'};
  char buffer2[1000] = {'\0'};
  int g_spec_test = sprintf(buffer1, "%g", 12.123123);
  int _g_spec_test = s21_sprintf(buffer2, "%.4g", 12.123123);

  ck_assert_int_eq(g_spec_test, _g_spec_test);
}
END_TEST

START_TEST(s21_sprintf_ten_p) {
#line 151
  char buffer1[100] = {'\0'};
  char buffer2[100] = {'\0'};
  int x = 1234567;
  void *ptr = &x;
  double y = 123.1234567;
  void *ptr2 = &y;
  int test1 = sprintf(buffer1, "%p", ptr);
  int _test1 = s21_sprintf(buffer2, "%p", ptr);
  int test2 = sprintf(buffer1, "%-20p", ptr2);
  int _test2 = s21_sprintf(buffer2, "%-20p", ptr2);

  ck_assert_int_eq(test1, _test1);
  ck_assert_int_eq(test2, _test2);
}
END_TEST

START_TEST(s21_sprintf_eleven_all) {
#line 166
  char buffer1[1000] = {'\0'};
  int all_spec_test =
      sprintf(buffer1, "%% char %-10c uint %-10u float %-+19f str %8s", '!',
              123, 12.123, "asd");
  int _all_spec_test =
      s21_sprintf(buffer1, "%% char %-10c uint %-10u float %-+19f str %8s", '!',
                  123, 12.123, "asd");
  int type_Ldouble_test = sprintf(buffer1, "%Lf", (long double)10.12);
  int _type_Ldouble_test = s21_sprintf(buffer1, "%Lf", (long double)10.12);

  ck_assert_int_eq(all_spec_test, _all_spec_test);
  ck_assert_int_eq(type_Ldouble_test, _type_Ldouble_test);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_sprintf_one_c);
  tcase_add_test(tc1_1, s21_sprintf_two_d);
  tcase_add_test(tc1_1, s21_sprintf_three_f);
  tcase_add_test(tc1_1, s21_sprintf_four_s);
  tcase_add_test(tc1_1, s21_sprintf_five_u);
  tcase_add_test(tc1_1, s21_sprintf_six_e);
  tcase_add_test(tc1_1, s21_sprintf_seven_x);
  tcase_add_test(tc1_1, s21_sprintf_eight_o);
  tcase_add_test(tc1_1, s21_sprintf_nine_g);
  tcase_add_test(tc1_1, s21_sprintf_ten_p);
  tcase_add_test(tc1_1, s21_sprintf_eleven_all);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
