#	!!!!!!!!!

#	ЭТОТ ФАЙЛ СУЩЕСТВУЕТ РАДИ ДЛЯ ТЕСТА CORE_FUNCS

#	!!!!!!!!!!!!!

FILES = ./*c ../*c
CC = gcc
FLAGS = -std=c11 -Wall -Werror -Wextra -pedantic

all: 
	$(CC) $(FLAGS) $(FILES) -o test

# all: test_memchr test_memcmp test_memcpy test_memset test_strncat test_strchr test_strncmp \
#      test_strncpy test_strcspn test_strerror test_strlen test_strpbrk test_strrchr test_strstr test_strtok

# test_memchr: ../s21_memchr.c test_memchr.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_memchr.c test_memchr.c -o test_memchr

# test_memcmp: ../s21_memcmp.c test_memcmp.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_memcmp.c test_memcmp.c -o test_memcmp

# test_memcpy: ../s21_memcpy.c test_memcpy.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_memcpy.c test_memcpy.c -o test_memcpy

# test_memset: ../s21_memset.c test_memset.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_memset.c test_memset.c -o test_memset

# test_strncat: ../s21_strncat.c test_strncat.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strncat.c test_strncat.c -o test_strncat

# test_strchr: ../s21_strchr.c test_strchr.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strchr.c test_strchr.c -o test_strchr

# test_strncmp: ../s21_strncmp.c test_strncmp.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strncmp.c test_strncmp.c -o test_strncmp

# test_strncpy: ../s21_strncpy.c test_strncpy.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strncpy.c test_strncpy.c -o test_strncpy

# test_strcspn: ../s21_strcspn.c test_strcspn.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strcspn.c test_strcspn.c -o test_strcspn

# test_strerror: ../s21_strerror.c test_strerror.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strerror.c test_strerror.c -o test_strerror

# test_strlen: ../s21_strlen.c test_strlen.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strlen.c test_strlen.c -o test_strlen

# test_strpbrk: ../s21_strpbrk.c test_strpbrk.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strpbrk.c test_strpbrk.c -o test_strpbrk

# test_strrchr: ../s21_strrchr.c test_strrchr.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strrchr.c test_strrchr.c -o test_strrchr

# test_strstr: ../s21_strstr.c test_strstr.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strstr.c test_strstr.c -o test_strstr

# test_strtok: ../s21_strtok.c test_strtok.c ../s21_string.h
# 	$(CC) $(CFLAGS) ../s21_strtok.c test_strtok.c -o test_strtok

clean:
	rm -f test_memchr test_memcmp test_memcpy test_memset test_strncat \
	      test_strchr test_strncmp test_strncpy test_strcspn test_strerror \
	      test_strlen test_strpbrk test_strrchr test_strstr test_strtok test
